server:
  port: 10000
spring:
  application:
    name: hello-world-service
 
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true