server:
  port: 11000
 
spring:
  application:
    name: authentication-service
    
## Disable Spring Security for All Calls.    
security:
  ignored:
  - /**
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
#app.security.config
app:
  security:
    secret: Abracadabr@
   